linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - errcheck
    - gosimple
    - varcheck

linters-settings:
  gofmt:
    simplify: false

run:
  timeout: 5m
