linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - errcheck
    - gosimple
    - varcheck

linters-settings:
  gofmt:
    simplify: false
  goimports:
    local-prefixes: github.com/cosmos/cosmos-sdk

run:
  timeout: 5m
