name: Protobuf
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - "feat/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2.4.0
      - name: lint
        run: make proto-lint

  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: check-breakage
        run: make proto-check-breaking
